name = "Implication"
author = "comp500"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f73362916fac117ebdcf20ef4f8f6489199f351089a3556aff105c3bee9d4d3d"

[versions]
minecraft = "1.19.2"
quilt = "0.20.0-beta.15"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
