name = "Implication"
author = "comp500"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ddd6ab587326a9914260585456e442a2404b0c7c3df4a6f3849e01485a87bdf"

[versions]
minecraft = "1.19.2"
quilt = "0.20.0-beta.15"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
